### ISSUE TITLE
Fix module and struct name to make project buildable

### ISSUE THREAD

**Issue by vgratian** [UlricQin/falcon-eye#11]
I think you are not maintaining this project anymore, but just in case you want people to still be able to build it (which I tried), 2 fixes would do it:

* create a module: `go mod init github.com/ulricqin/falcon-eye`
* in [global/global.go:12](https://github.com/UlricQin/falcon-eye/blob/b6a46b750b8ebaeff2fc72e36c5385fc425fac02/global/global.go#L12), rename `var Config config.ConfigContainer` --> `var Config config.Configer`.

**Comment by UlricQin** [comment]
fixed building error. 3ks

**Comment by vgratian** [comment]
awesome, thankx
